title: VÃ­tor Bandeira Borges
logo: /assets/img/logo.png
description: Economist & Data Scientist
description: >
  Economist & Data Scientist
  <br>
  <br>
  <a href="https://github.com/vitorbborges/vitorbborges.github.io/raw/main/assets/Vitor_s_Resume.pdf" target="_blank">ğŸ“œ Curriculum Vitae</a> 
  <br>
  <a href="https://github.com/vitorbborges" target="_blank">ğŸ’» Github</a>
  <br>
  <a href="https://www.linkedin.com/in/v%C3%ADtor-bandeira-borges/" target="_blank">ğŸ’¼ LinkedIn</a>
  - ğŸ”­ &nbsp; Iâ€™m currently researching Time-Series Models, Recommender Systems and Natural Language Processing.
  - ğŸ¤” &nbsp; Exploring new technologies, data solutions and quick hacks.
  - ğŸ“ &nbsp; Studying Economics at the University of Brasilia.
  - ğŸ’¼ &nbsp; Freelancer at [ENAP](https://enap.gov.br/pt/) and Research Assistant at [Brazil's Science and Technology Ministry](https://www.convergenciadigital.com.br/Gestao/Sem-orcamento%2C-MCTI-usa-inteligencia-artificial-para-captar-dinheiro-59425.html?UserActiveTemplate=mobile).
  - ğŸ” &nbsp; Deputy Coordinator at the [Laboratory for Machine Learning in Finance and Organizations (LAMFO).](https://github.com/lamfo-unb)
  - ğŸŒ± &nbsp; Enthusiast in Mathematics, Statistics and Artificial Intelligence .
  - â³  &nbsp;  Solving the Rubik's cube every day marginally faster (Single solve record: 15.06s).
  - â˜• &nbsp; I belive, a perfect cup of coffee can be the ultimate solution for any stress.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
